import Head from 'next/head'
import Latest from '../components/Latest';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='./img/favicon.ico' />
      </Head>
      <main>
        <Latest />
      </main>
    </div>
  )
}